### ISSUE TITLE
remove reproducible wheels patch

### ISSUE THREAD

**Issue by jacobbogdanov** [128technology/rules_128tech#11]
since https://github.com/128technology/rules_pip/pull/1 has been merged to rules_pip,
we should remove the patch from this repo

**Comment by ian-h-chamberlain** [comment]
Related: the dep name in this repo is `com_apt_itude_rules_pip` while downstream uses `com_128technology_rules_pip`, so any usage of rules defined in this repo will actually be using a different version.
