### ISSUE TITLE
pytest-isort can't be configured with pyproject.toml

### ISSUE THREAD

**Issue by jacobbogdanov** [128technology/rules_128tech#7]
```
<path omitted>/isort/isort/settings.py:298: 
UserWarning: Found /code/pyproject.toml with [tool.isort] section, but toml package is not installed. To configure isort with /code/pyproject.toml, install with 'isort[pyproject]'.
  file_path))
```

edit: this is coming from `pylint_test`. It looks like we're using `pytest_test` to enforce isort using `pytest-isort`, so I'm not sure why `pylint` is hitting this code path?

**Comment by jacobbogdanov** [comment]
@jamesesilvia, are you guys using a `pyproject.toml` file in your repo?
- if yes, I'll add the missing dep here,
- if no, I'll add the missing dep to our internal `pytest_test` wrapper rule

**Comment by jamesesilvia** [comment]
Yeah we are -- but relying on pre-commit for isort so I dont think Im seeing this. Whats the resulting issue?

**Comment by jacobbogdanov** [comment]
okay, I think I know what's going on.
`pylint` 1.6 added a dep on `isort` https://github.com/PyCQA/pylint/blob/3fffdf03d5a32e4a0d1b5216ea9d16dacacdaa6f/doc/whatsnew/1.6.rst#other-changes
so even though we are using `pytest-isort` to check import order, it seems that `pylint` was _also_ checking import order.

In our dev environment `toml` was installed into the system python so we weren't seeing this warning... until we `toml` was removed from that environment! 🤦

I think the fix I'm going to do is;
- remove `pytest-isort`,
- add `isort[pyproject]` (if `rules_pip` even allows a package with that name...) else I'll just add `toml` directly as a dep of `pylint_test`
